config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :graphs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
   root "graphs#index"

   post "/refresh_goals_info", to: "graphs#refresh_goals_info", as: "refresh_goals_info"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/api_module.rb
module ApiModule
    extend ActiveSupport::Concern

    BASE_URL = "https://fintual.cl/api"


    def self.get_goals token
        HTTParty.get(BASE_URL+"/goals", body: { user_email: ENV["FINTUAL_EMAIL"], user_token: token })
    end

    private

    def self.retrieve_user_token
        HTTParty.post(BASE_URL+"/access_tokens", body: {user: { email: ENV["FINTUAL_EMAIL"], password: ENV["FINTUAL_PASSWORD"]}}).parsed_response
    end
end

app/models/goal.rb
class Goal < ApplicationRecord

    has_many :goal_profits

    after_create :calculate_variation

    def self.get_goals_profits_from_api token
        @goals = ApiModule.get_goals token

        @goals['data'].each_with_index do |goal,index|
            db_goal = Goal.find_by(name: goal['attributes']['name'])
            
            if db_goal
                current_day_profit = db_goal.goal_profits.pluck(:registered_date, :profit).detect{|rd| rd[0] == Date.today && rd[1] == goal["attributes"]["profit"] }
                
                unless current_day_profit.present? 
                    db_goal.goal_profits << GoalProfit.create(registered_date: Date.today, profit: goal['attributes']['profit'])
                end
            else
                return { todo: "Malo", id_malo: goal }
            end
        end

        return { todo: "Bem" }
    end

    def calculate_variation
        old_element = nil
        GoalProfit.where(goal_id: id).order(:created_at).each_with_index do |gp, i|

        if i > 0
            gp.variation = gp.profit-old_element.profit
            p gp.variation
            gp.save
            old_element = gp
        else
            old_element = gp
        end
        
        end
    end
end

app/models/goal_profit.rb
class GoalProfit < ApplicationRecord
  belongs_to :goal
end

app/models/graph.rb
class Graph < ApplicationRecord
    include ApiModule


    def self.get_goals_from_api
        response = ApiModule.get("/goals")
    end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base


    before_action :retrieve_access_token


    def retrieve_access_token
        if !session[:fintual_token] 
            session[:fintual_token] = ApiModule.retrieve_user_token["data"]["attributes"]["token"] 
        end
    end
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  before_action :set_graph, only: %i[ show edit update destroy ]

  def refresh_goals_info
    Goal.get_goals_profits_from_api(session[:fintual_token]) 
    redirect_to root_path
  end

  # GET /graphs or /graphs.json
  def index
    total_sum = 0
    @gpa = GoalProfit.where('goal_id = ? AND variation != 0', Goal.find_by(name: "Savings").id).pluck(:registered_date, :variation)
    @gpa.each do |as|
      total_sum += as[1]
      as[1] = total_sum
    end 
    @graphs = Graph.all
  end

  # GET /graphs/1 or /graphs/1.json
  def show
  end

  # GET /graphs/new
  def new
    @graph = Graph.new
  end

  # GET /graphs/1/edit
  def edit
  end

  # POST /graphs or /graphs.json
  def create
    @graph = Graph.new(graph_params)

    respond_to do |format|
      if @graph.save
        format.html { redirect_to graph_url(@graph), notice: "Graph was successfully created." }
        format.json { render :show, status: :created, location: @graph }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @graph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /graphs/1 or /graphs/1.json
  def update
    respond_to do |format|
      if @graph.update(graph_params)
        format.html { redirect_to graph_url(@graph), notice: "Graph was successfully updated." }
        format.json { render :show, status: :ok, location: @graph }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @graph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /graphs/1 or /graphs/1.json
  def destroy
    @graph.destroy!

    respond_to do |format|
      format.html { redirect_to graphs_url, notice: "Graph was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_graph
      @graph = Graph.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def graph_params
      params.require(:graph).permit(:name, :list_order)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/views/graphs/_form.html.erb
<%= form_with(model: graph) do |form| %>
  <% if graph.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(graph.errors.count, "error") %> prohibited this graph from being saved:</h2>

      <ul>
        <% graph.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :list_order, style: "display: block" %>
    <%= form.number_field :list_order %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/graphs/_graph.html.erb
<div id="<%= dom_id graph %>">
  <p>
    <strong>Name:</strong>
    <%= graph.name %>
  </p>

  <p>
    <strong>List order:</strong>
    <%= graph.list_order %>
  </p>

</div>

app/views/graphs/edit.html.erb
<h1>Editing graph</h1>

<%= render "form", graph: @graph %>

<br>

<div>
  <%= link_to "Show this graph", @graph %> |
  <%= link_to "Back to graphs", graphs_path %>
</div>

app/views/graphs/index.html.erb
<p style="color: green"><%= notice %></p>

<div style="display: grid;justify-content: center;">
<h1>Graphs</h1>

<h3> Goals in db: <%= Goal.count %> </h3>
<h3> Profits in db: <%= GoalProfit.count %> </h3>
<span style="padding-left: 11%;">
<%= button_to "Refresh Info", {:controller => "graphs", :action => "refresh_goals_info"} ,remote: :true %> 
</span>
</div>
<div id='graphs'>
  <% @graphs.each do |graph| %>
    <%= render graph %>
    <p>
      <%= link_to "Show this graph", graph %>
    </p>
  <% end %>
</div>



<div class= "mini-body" style="margin: 75px 6%">
<div style="display: flex;align-items: center;justify-content: space-between;">
<%= line_chart @gpa, width: "40%", height: "500px", min: 0 %>

<%= column_chart @gpa, width: "40%", height: "500px", min: 0, discrete: true %>

<%= line_chart GoalProfit.where(goal_id: Goal.find_by(name: "Savings").id).pluck(:registered_date, :profit), width: "40%", height: "500px", min: 0 %>
</div>
</div>

app/views/graphs/new.html.erb
<h1>New graph</h1>

<%= render "form", graph: @graph %>

<br>

<div>
  <%= link_to "Back to graphs", graphs_path %>
</div>

app/views/graphs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @graph %>

<div>
  <%= link_to "Edit this graph", edit_graph_path(@graph) %> |
  <%= link_to "Back to graphs", graphs_path %>

  <%= button_to "Destroy this graph", @graph, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FintualGraphs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>